name: Snap Hutao Remastered Canary
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
      - release
      - dependabot/**
    paths-ignore:
      - '.gitattributes'
      - '.github/**'
      - '.gitignore'
      - '.gitmodules'
      - '**.md'
      - 'LICENSE'
      - '**.yml'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: dev
          fetch-depth: 0

      - name: Merge all branches into dev locally
        id: merge
        run: |
          $continue = $true

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin '+refs/heads/*:refs/remotes/origin/*'
          git checkout origin/dev
          $response = curl -s https://api.github.com/repos/SnapHutaoRemasteringProject/Snap.Hutao.Remastered/pulls?state=open
          $refs = $response | ConvertFrom-Json | Where-Object { $_.draft -eq $false } | ForEach-Object { $_.head.ref }
          if ($refs.Count -eq 0 -or ($refs.Count -eq 1 -and $refs -eq "l10n_dev")) {
              echo "No PRs to merge"
              $continue = $false
              echo "continue=$continue" >> $Env:GITHUB_OUTPUT
              exit
          }

          foreach ($ref in $refs) {
              echo "Merging $ref into dev"
              git merge "origin/$ref" --strategy=ort --allow-unrelated-histories -m "Merge $ref into dev"
          }

          echo "continue=$continue" >> $Env:GITHUB_OUTPUT

      - name: Setup .NET
        if: ${{ steps.merge.outputs.continue == 'true' }}
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0

      - name: Cache NuGet packages
        if: ${{ steps.merge.outputs.continue == 'true' }}
        uses: actions/cache@v6
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/Snap.Hutao.Remastered.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Cake (MSIX)
        if: ${{ steps.merge.outputs.continue == 'true' }}
        id: cake
        shell: pwsh
        run: dotnet tool restore && dotnet cake
        env:
          CERTIFICATE: ${{ secrets.CERTIFICATE }}
          PW: ${{ secrets.PW }}

      - name: Build installer
        if: ${{ steps.merge.outputs.continue == 'true' }}
        id: installer
        shell: pwsh
        run: dotnet cake build-installer.cake
        env:
          CERTIFICATE: ${{ secrets.CERTIFICATE }}
          PW: ${{ secrets.PW }}

      - name: Upload signed msix
        if: ${{ success() && steps.merge.outputs.continue == 'true' }}
        uses: actions/upload-artifact@v7
        with:
          name: Snap.Hutao.Remastered.Canary-${{ steps.cake.outputs.version }}
          path: ${{ github.workspace }}/src/output/Snap.Hutao.Remastered.Canary-${{ steps.cake.outputs.version }}.msix

      - name: Upload installer
        if: ${{ success() && steps.merge.outputs.continue == 'true' }}
        uses: actions/upload-artifact@v7
        with:
          name: Snap.Hutao.Remastered.Canary-Setup-${{ steps.cake.outputs.version }}
          path: ${{ github.workspace }}/publish/Snap.Hutao.Remastered-*.exe

      - name: Upload code-signing certificate
        if: ${{ success() && steps.merge.outputs.continue == 'true' }}
        uses: actions/upload-artifact@v7
        with:
          name: Snap.Hutao.Remastered.Canary-SnapHutaoRemasteringProject-${{ steps.installer.outputs.version }}
          path: ${{ github.workspace }}/temp-code-signing.cer

      - name: Add summary
        if: ${{ success() && steps.merge.outputs.continue == 'true' }}
        shell: pwsh
        run: |
          $summary = "
          > [!WARNING]
          > 该版本是由 CI 程序自动打包生成的 \`Canary\` 测试版本，包含新功能原型及问题修复

          > [!IMPORTANT]
          > 直接旁加载 MSIX 时，请将 SnapHutaoRemasteringProject 工件中的证书安装到 **受信任的人员（TrustedPeople）** 存储
          "

          echo $summary >> $Env:GITHUB_STEP_SUMMARY
